server:
  port: 8081

spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: none
        show_sql: true
    generate-ddl: true
