version: '2'

services:
  mrpehlivan:
    image: postgres:9.6-alpine
    container_name: 'mrpehlivan-db'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes:
      - mrpehlivan-db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
  jenkins:
    image: jenkins:2.60.3
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins

volumes:
  mrpehlivan-db-data:
    driver: local
